// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:absensi_hash/models/location/m_location.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MLocationAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MLocationAdapter());
  }
}
